import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import { ModulesProvider } from "@/context/modulesContext";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // Ajusta los pesos según lo que necesites
  variable: '--font-poppins', // Define una variable CSS para usarla en Tailwind
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable} >
      <body
        className={poppins.variable}
      >
        <ModulesProvider>
        {children}
        </ModulesProvider>
       
      </body>
    </html>
  );
}
